# Generated by Django 3.2.8 on 2021-10-25 20:35

import core.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', core.models.BaseManager()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perguntas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codigo_sala', models.UUIDField(auto_created=True, blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entrar', models.BooleanField(blank=True, default=True, null=True)),
                ('descricao', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSala',
            fields=[
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_sala',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.perfil')),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_perfil',
            },
        ),
        migrations.CreateModel(
            name='PerguntaSala',
            fields=[
                ('data', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.perguntas')),
                ('id_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
            ],
            options={
                'db_table': 'pergunta_sala',
            },
        ),
    ]
